name: lexa
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  lottie: ^3.0.0
  dio: ^5.4.1
  #  flutter_tts: ^4.0.1
  cached_network_image: ^3.3.1
  sticky_headers: "^0.3.0"
  flutter_card_swiper: ^7.0.0
  modal_bottom_sheet: ^2.1.2
  localstorage: ^4.0.0+1
  image_picker: ^1.0.7
  gradient_borders: ^1.0.0
  shared_preferences: ^2.2.2
  logger: any
  equatable: ^2.0.3
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.7.0
  go_router: ^13.2.1
  flutter_custom_tabs: ^2.0.0+1
  uni_links: any
  url_launcher: ^6.2.5
  provider: ^6.1.2
  photo_manager: ^3.0.0
  toastification: ^1.2.1
  socket_io_client: ^3.0.0-beta.2
  pull_to_refresh_flutter3: ^2.0.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.0.2
  onesignal_flutter: ^5.1.2
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.6.2
  flutter_launcher_icons: "^0.13.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/
    - assets/animations/
    - assets/sounds/
    - .env
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
        - asset: fonts/Quicksand-Bold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Medium.ttf
        - asset: fonts/Mulish-SemiBold.ttf
        - asset: fonts/Mulish-Bold.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
